[pytest]
testpaths = test_kanban_board
addopts = -v --tb=short
markers =
    smoke: быстрые проверки
    status: тесты станицы статусов
    users: тесты станицы пользователей
    tasks: тесты станицы задач
    labels: тесты станицы лейблов